### ISSUE TITLE
How to get a cif file of a specific adsorbent, via hash key or some other identifiers?

### ISSUE THREAD

**Issue by zhangshd** [NIST-ISODB/isodb-library#12]

**Comment by danieleongari** [comment]
Hi @zhangshd the CIF-to-adsorbent is not a trivial operation that is supported for the whole NIST-ISODB database. 
For MOF adsorbents we investigated a solution to the problem in this pubblication: https://pubs.acs.org/doi/abs/10.1021/acs.jced.1c00958

**Comment by zhangshd** [comment]
> Hi @zhangshd the CIF-to-adsorbent mapping is not a trivial operation that is supported for the whole NIST-ISODB database. For MOF adsorbents we investigated a solution to the problem in this pubblication: [https://pubs.acs.org/doi/abs/10.1021/acs.jced.1c00958[ ](https://www.sci-hub.ee/10.1021/acs.jced.1c00958)](https://pubs.acs.org/doi/abs/10.1021/acs.jced.1c00958) (open-access preprint: https://doi.org/10.26434/chemrxiv-2021-gs0wj-v3)

Thank you @danieleongari, this is a very meaningful work. I learned a lot in this paper.
